### ISSUE TITLE
Unable to import expect-more jest

### ISSUE THREAD

**Issue by fluffynuts** [JamieMason/expect-more#57]
## Description
The scaffolder `newts` installs `expect-even-more-jest` which depends on `expect-more-jest`. After creating a project with the latest of both (`npx newts@beta`), tests cannot run:

```
 FAIL  tests/index.spec.ts
  ● Test suite failed to run

    Cannot find module 'expect/build/jasmineUtils' from 'node_modules/expect-more-jest/dist/to-be-array-of.js'

    Require stack:
      node_modules/expect-more-jest/dist/to-be-array-of.js
      node_modules/expect-more-jest/dist/index.js
      node_modules/expect-even-more-jest/dist/index.js
      tests/index.spec.ts

      at Resolver._throwModNotFoundError (node_modules/jest/node_modules/jest-resolve/build/resolver.js:491:11)
      at Object.<anonymous> (node_modules/expect-more-jest/dist/to-be-array-of.js:5:22)
```

delving a little deeper, by doing:
```javascript
global.expect = require("expect");
require("expect-more-jest");
```

produces
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './build/jasmineUtils' is not defined by "exports" in C:\tmp\moo-cakes-wtf\node_modules\expect\package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:299:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:522:3)
    at resolveExports (internal/modules/cjs/loader.js:424:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:464:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:802:27)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\tmp\moo-cakes-wtf\node_modules\expect-more-jest\dist\to-be-array-of.js:5:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

## Suggested Solution

Perhaps copy-pasta the required code or use a git submodule to get to it?

If I get a moment, I'll try raise a PR

**Comment by JamieMason** [comment]
Thanks @fluffynuts, been hit by this too in my own projects – hopefully this is now fixed in [expect-more-jest@5.4.1](https://github.com/JamieMason/expect-more/releases/tag/expect-more-jest%405.4.1).

**Comment by fluffynuts** [comment]
I'll test via newts and let you know. When newts bootstraps a new project, it installs the latest version of things. However, I may need to update my downstream, expect-even-more-jest, as I _think_ newts just installs that and pulls in this package as a dependency.

At any rate, thanks for your work!

**Comment by fluffynuts** [comment]
Work great here. Thanks.
